#include "packettype.h"

char *packettype_cstr(PacketType_e type) {
    switch (type) {
    case PACKETTYPE_001_NPC_INFO:
        return "PACKETTYPE_001_NPC_INFO";
    case PACKETTYPE_002_IFACE_SETCOLOUR:
        return "PACKETTYPE_002_IFACE_SETCOLOUR";
    case PACKETTYPE_004_MESSAGE_PRIVATE:
        return "PACKETTYPE_004_MESSAGE_PRIVATE";
    case PACKETTYPE_007_UPDATE_ZONE_PARTIAL_FOLLOWS:
        return "PACKETTYPE_007_UPDATE_ZONE_PARTIAL_FOLLOWS";
    case PACKETTYPE_022_UPDATE_RUNWEIGHT:
        return "PACKETTYPE_022_UPDATE_RUNWEIGHT";
    case PACKETTYPE_023_ZONE_PROTO_LOC_MERGE:
        return "PACKETTYPE_023_ZONE_PROTO_LOC_MERGE";
    case PACKETTYPE_032_CHAT_FILTER_SETTINGS:
        return "PACKETTYPE_032_CHAT_FILTER_SETTINGS";
    case PACKETTYPE_042_ZONE_PROTO_LOC_ANIM:
        return "PACKETTYPE_042_ZONE_PROTO_LOC_ANIM";
    case PACKETTYPE_050_ZONE_PROTO_OBJ_REVEAL:
        return "PACKETTYPE_050_ZONE_PROTO_OBJ_REVEAL";
    case PACKETTYPE_054_MIDI_SONG:
        return "PACKETTYPE_054_MIDI_SONG";
    case PACKETTYPE_068_UPDATE_RUNENERGY:
        return "PACKETTYPE_068_UPDATE_RUNENERGY";
    case PACKETTYPE_080_DATA_LAND_DONE:
        return "PACKETTYPE_080_DATA_LAND_DONE";
    case PACKETTYPE_132_DATA_LAND:
        return "PACKETTYPE_132_DATA_LAND";
    case PACKETTYPE_135_UPDATE_ZONE_FULL_FOLLOWS:
        return "PACKETTYPE_135_UPDATE_ZONE_FULL_FOLLOWS";
    case PACKETTYPE_136_RESET_ANIMS:
        return "PACKETTYPE_136_RESET_ANIMS";
    case PACKETTYPE_139_UPDATE_UID192:
        return "PACKETTYPE_139_UPDATE_UID192";
    case PACKETTYPE_150_VARP_SMALL:
        return "PACKETTYPE_150_VARP_SMALL";
    case PACKETTYPE_151_ZONE_PROTO_OBJ_COUNT:
        return "PACKETTYPE_151_ZONE_PROTO_OBJ_COUNT";
    case PACKETTYPE_167_IFACE_OPENSIDEOVERLAY:
        return "PACKETTYPE_167_IFACE_OPENSIDEOVERLAY";
    case PACKETTYPE_175_VARP_LARGE:
        return "PACKETTYPE_175_VARP_LARGE";
    case PACKETTYPE_184_PLAYER_INFO:
        return "PACKETTYPE_184_PLAYER_INFO";
    case PACKETTYPE_193_RESET_CLIENT_VARCACHE:
        return "PACKETTYPE_193_RESET_CLIENT_VARCACHE";
    case PACKETTYPE_201_IFACE_SETTEXT:
        return "PACKETTYPE_201_IFACE_SETTEXT";
    case PACKETTYPE_220_DATA_LOC:
        return "PACKETTYPE_220_DATA_LOC";
    case PACKETTYPE_223_ZONE_PROTO_OBJ_ADD:
        return "PACKETTYPE_223_ZONE_PROTO_OBJ_ADD";
    case PACKETTYPE_237_REBUILD_NORMAL:
        return "PACKETTYPE_237_REBUILD_NORMAL";
    case PACKETTYPE_239_CAM_RESET:
        return "PACKETTYPE_239_CAM_RESET";
    default:
        return "Invalid packet type";
    }
}